print(welcome_str.format(students[1]))
print(welcome_str.format(students[2]))
students .append("mary")
students .append("evelyne")
print(welcome_str.format(students[3]))
print(welcome_str.format(students[4]))
print(welcome_str.format(students[0]))